*** Chapter 20 Syntax examples *** ;
/*** most useful procedures *** ;

A. Introduction
B. PROC ANOVA
C. PROC APPEND
D. PROC CHART
E. PROC CONTENTS
F. PROC CORR
G. PROC DATASETS
H. PROC FACTOR
I. PROC FORMAT
J. PROC FREQ
K. PROC GCHART
L. PROC GLM
M. PROC GPLOT
N. PROC LOGISTIC
O. PROC MEANS
P. PROC NPARIWAY
Q. PROC PLOT
R. PROC PRINT
S. PROC RANK
T. PROC REG
U. PROC SORT
v. PROC TTEST
W. PROC UNIVARIATE

**********************/
